import type {
  AppNotification,
  Client,
  Project,
  Proposal,
  Settings,
} from "~/lib/types";
import proposalBody from "~/lib/proposalBody";

const D = 86400000;
const H = 3600000;

export interface SeedData {
  clients: Client[];
  projects: Project[];
  proposals: Proposal[];
  notifications: AppNotification[];
  settings: Settings;
}

/** Ported 1:1 from the Claude Design mock's `Component.seed()`, so first load
 * matches the design exactly (same fake data, same relative-to-`now` dates). */
export default function seed(): SeedData {
  const now = Date.now();

  const clients: Client[] = [
    {
      id: "c1",
      name: "Maya Okonkwo",
      email: "maya@ferrousandco.com",
      company: "Ferrous & Co.",
      notes: "Prefers Friday check-ins. Two stakeholders, one decision-maker.",
    },
    {
      id: "c2",
      name: "Daniel Reyes",
      email: "d.reyes@northbaydental.com",
      company: "North Bay Dental",
      notes: "Booking flow is the priority — everything else can wait.",
    },
    {
      id: "c3",
      name: "Priya Raman",
      email: "priya@lumenbooks.co",
      company: "Lumen Books",
      notes: "Referred by Maya.",
    },
    {
      id: "c4",
      name: "Owen Tate",
      email: "owen@tateaudio.io",
      company: "Tate Audio",
      notes: "",
    },
  ];

  const projects: Project[] = [
    {
      id: "p1",
      clientId: "c1",
      title: "Marketing site rebuild",
      stage: "active",
      completed: false,
      price: 6800,
      due: "2026-10-09",
      deliverables: [
        "Design system + six page templates",
        "Front-end build with CMS wiring",
        "Analytics and performance pass",
      ],
      status: "In Progress",
      progress: 45,
      password: "ferrous-3417",
      contract: { name: "Maya Okonkwo", ts: now - 19 * D },
      deposit: true,
      final: false,
      proposalId: "pr1",
      messages: [
        {
          id: "m1",
          from: "Alex Mercer",
          side: "freelancer",
          ts: now - 18 * D,
          text: "Contract is signed and the deposit landed — thanks Maya. Starting on the content model today.",
          file: null,
        },
        {
          id: "m2",
          from: "Maya Okonkwo",
          side: "client",
          ts: now - 11 * D,
          text: "Here are the product photos we discussed. The two hero shots are the ones we own outright.",
          file: "ferrous-photography.zip",
        },
        {
          id: "m3",
          from: "system",
          side: "system",
          ts: now - 6 * D,
          text: "Status changed to In Progress",
          file: null,
        },
        {
          id: "m4",
          from: "Alex Mercer",
          side: "freelancer",
          ts: now - 3 * D,
          text: "Six templates are on staging. Home and Case Study are the two I want your eyes on first.",
          file: "staging-notes.pdf",
        },
        {
          id: "m5",
          from: "Maya Okonkwo",
          side: "client",
          ts: now - 2 * D - 4 * H,
          text: "Looks great. One note on the case study header — can the client logo sit above the title rather than beside it?",
          file: null,
        },
      ],
    },
    {
      id: "p2",
      clientId: "c2",
      title: "Booking flow + site refresh",
      stage: "active",
      completed: false,
      price: 4200,
      due: "2026-09-18",
      deliverables: [
        "Appointment booking flow (4 screens)",
        "Responsive site refresh",
        "Staff training doc",
      ],
      status: "Delivered",
      progress: 90,
      password: "northbay-2088",
      contract: { name: "Daniel Reyes", ts: now - 33 * D },
      deposit: true,
      final: false,
      proposalId: "pr2",
      messages: [
        {
          id: "m6",
          from: "Alex Mercer",
          side: "freelancer",
          ts: now - 30 * D,
          text: "Kicking off. First question: do you want deposits taken at booking, or on arrival?",
          file: null,
        },
        {
          id: "m7",
          from: "Daniel Reyes",
          side: "client",
          ts: now - 29 * D,
          text: "On arrival for now. We can revisit once the front desk is comfortable with it.",
          file: null,
        },
        {
          id: "m8",
          from: "system",
          side: "system",
          ts: now - 4 * D,
          text: "Status changed to Delivered",
          file: null,
        },
        {
          id: "m9",
          from: "Alex Mercer",
          side: "freelancer",
          ts: now - 4 * D + H,
          text: "Everything is live. Training doc attached — when you approve, I will send the final invoice.",
          file: "northbay-training.pdf",
        },
      ],
    },
    {
      id: "p3",
      clientId: "c1",
      title: "Landing page A/B test",
      stage: "completed",
      completed: true,
      price: 1500,
      due: "2026-06-26",
      deliverables: [
        "Two landing page variants",
        "Event tracking + results readout",
      ],
      status: "Approved",
      progress: 100,
      password: "ferrous-1102",
      contract: { name: "Maya Okonkwo", ts: now - 96 * D },
      deposit: true,
      final: true,
      proposalId: "pr3",
      messages: [
        {
          id: "m10",
          from: "Alex Mercer",
          side: "freelancer",
          ts: now - 70 * D,
          text: "Results are in — variant B took a 19% lift on trial starts. Readout attached.",
          file: "ab-readout.pdf",
        },
        {
          id: "m11",
          from: "Maya Okonkwo",
          side: "client",
          ts: now - 69 * D,
          text: "Approving. Final payment goes out Friday.",
          file: null,
        },
      ],
    },
    {
      id: "p4",
      clientId: "c3",
      title: "Catalogue site + store migration",
      stage: "proposal",
      completed: false,
      price: 9400,
      due: "2026-11-20",
      deliverables: [
        "Catalogue templates for 400+ titles",
        "Store migration with redirects",
        "Editor training + handover",
      ],
      status: "Not started",
      progress: 0,
      password: "lumen-7719",
      contract: null,
      deposit: false,
      final: false,
      proposalId: "pr4",
      messages: [],
    },
    {
      id: "p5",
      clientId: "c4",
      title: "Product microsite",
      stage: "proposal",
      completed: false,
      price: 5600,
      due: "2026-10-30",
      deliverables: ["Single-page microsite", "Pre-order form + email capture"],
      status: "Not started",
      progress: 0,
      password: "tate-4102",
      contract: null,
      deposit: false,
      final: false,
      proposalId: "pr5",
      messages: [],
    },
    {
      id: "p6",
      clientId: "c1",
      title: "CMS migration",
      stage: "proposal",
      completed: false,
      price: 0,
      due: "",
      deliverables: [],
      status: "Not started",
      progress: 0,
      password: "ferrous-9930",
      contract: null,
      deposit: false,
      final: false,
      proposalId: "pr6",
      messages: [],
    },
  ];

  const byId = (id: string) => projects.find((p) => p.id === id)!;

  const proposals: Proposal[] = [
    {
      id: "pr1",
      clientId: "c1",
      projectId: "p1",
      title: "Marketing site rebuild",
      price: 6800,
      due: "2026-10-09",
      deliverables: byId("p1").deliverables.slice(),
      body: proposalBody("Marketing site rebuild", "Ferrous & Co."),
      status: "Accepted",
      lastSaved: now - 20 * D,
      sentAt: now - 21 * D,
      comments: [],
    },
    {
      id: "pr2",
      clientId: "c2",
      projectId: "p2",
      title: "Booking flow + site refresh",
      price: 4200,
      due: "2026-09-18",
      deliverables: byId("p2").deliverables.slice(),
      body: proposalBody("Booking flow", "North Bay Dental"),
      status: "Accepted",
      lastSaved: now - 34 * D,
      sentAt: now - 35 * D,
      comments: [],
    },
    {
      id: "pr3",
      clientId: "c1",
      projectId: "p3",
      title: "Landing page A/B test",
      price: 1500,
      due: "2026-06-26",
      deliverables: byId("p3").deliverables.slice(),
      body: proposalBody("Landing page A/B test", "Ferrous & Co."),
      status: "Accepted",
      lastSaved: now - 97 * D,
      sentAt: now - 98 * D,
      comments: [],
    },
    {
      id: "pr4",
      clientId: "c3",
      projectId: "p4",
      title: "Catalogue site + store migration",
      price: 9400,
      due: "2026-11-20",
      deliverables: byId("p4").deliverables.slice(),
      body: proposalBody("Catalogue site", "Lumen Books"),
      status: "Sent",
      lastSaved: now - 2 * D,
      sentAt: now - 2 * D,
      comments: [],
    },
    {
      id: "pr5",
      clientId: "c4",
      projectId: "p5",
      title: "Product microsite",
      price: 5600,
      due: "2026-10-30",
      deliverables: byId("p5").deliverables.slice(),
      body: proposalBody("Product microsite", "Tate Audio"),
      status: "Client Commented",
      lastSaved: now - 5 * D,
      sentAt: now - 5 * D,
      comments: [
        {
          id: "cm1",
          author: "Owen Tate",
          side: "client",
          anchor: "I work in two-week passes with a review at the end of each.",
          text: "Can we get to a first look sooner? We have a trade show on the 14th.",
          ts: now - 31 * H,
          resolved: false,
        },
        {
          id: "cm2",
          author: "Owen Tate",
          side: "client",
          anchor: "50% deposit to start, 50% on completion.",
          text: "Deposit is fine. Can the second half be 30 days rather than 14?",
          ts: now - 30 * H,
          resolved: false,
        },
      ],
    },
    {
      id: "pr6",
      clientId: "c1",
      projectId: "p6",
      title: "CMS migration",
      price: 0,
      due: "",
      deliverables: [],
      body: "<h2>Overview</h2><p>Draft — outline the migration scope here.</p>",
      status: "Draft",
      lastSaved: null,
      sentAt: null,
      comments: [],
    },
  ];

  const notifications: AppNotification[] = [
    {
      id: "n1",
      projectId: "p5",
      audience: "freelancer",
      title: "Owen Tate left 2 comments on “Product microsite”",
      ts: now - 30 * H,
      read: false,
      route: "/proposals/pr5",
    },
    {
      id: "n2",
      projectId: "p1",
      audience: "freelancer",
      title: "New message from Maya Okonkwo on “Marketing site rebuild”",
      ts: now - 2 * D - 4 * H,
      read: false,
      route: "/projects/p1",
    },
    {
      id: "n3",
      projectId: "p4",
      audience: "freelancer",
      title:
        "Proposal sent to Priya Raman — “Catalogue site + store migration”",
      ts: now - 2 * D,
      read: true,
      route: "/proposals/pr4",
    },
    {
      id: "n4",
      projectId: "p2",
      audience: "freelancer",
      title: "Status changed to Delivered on “Booking flow + site refresh”",
      ts: now - 4 * D,
      read: true,
      route: "/projects/p2",
    },
    {
      id: "n5",
      projectId: "p1",
      audience: "freelancer",
      title: "Deposit marked received — $3,400 on “Marketing site rebuild”",
      ts: now - 18 * D,
      read: true,
      route: "/projects/p1",
    },
    {
      id: "n6",
      projectId: "p1",
      audience: "client",
      title: "Alex Mercer posted an update with an attachment",
      ts: now - 3 * D,
      read: false,
      route: "/thread",
    },
    {
      id: "n7",
      projectId: "p1",
      audience: "client",
      title: "Status changed to In Progress",
      ts: now - 6 * D,
      read: true,
      route: "/overview",
    },
    {
      id: "n8",
      projectId: "p1",
      audience: "client",
      title: "Contract signed — deposit invoice issued",
      ts: now - 19 * D,
      read: true,
      route: "/contract",
    },
    {
      id: "n9",
      projectId: "p4",
      audience: "client",
      title: "Alex Mercer sent you a proposal",
      ts: now - 2 * D,
      read: false,
      route: "/proposal",
    },
    {
      id: "n10",
      projectId: "p5",
      audience: "client",
      title: "Alex Mercer sent you a proposal",
      ts: now - 5 * D,
      read: true,
      route: "/proposal",
    },
  ];

  const settings: Settings = {
    name: "Alex Mercer",
    email: "alex@mercer.dev",
    invoiceName: "Mercer Digital",
    invoiceContact: "alex@mercer.dev · +1 415 555 0132",
    prefix: "MD-2026-",
    accent: "#5b93ff",
    logo: "",
    welcome:
      "Thanks for working with me — everything for this project lives here.",
    hideBranding: false,
  };

  return { clients, projects, proposals, notifications, settings };
}
